### ISSUE TITLE
validators.app warning?

### ISSUE THREAD

**Issue by jrchamp** [AGx10k/AGx10k.github.io#1]
vaidators.app is warning that the "validator identity matches the withdraw authority on your vote account". https://www.validators.app/faq#withdraw-authority-warning

I don't know how complex it is to resolve that issue, but I wanted to make sure you knew. Thank you for running a great validator!

**Comment by AGx10k** [comment]
Thank you for posting first issue ;)

The issue with withdrawer is not very relevant because it only affects funds at vote account which are non-existent since i'm running a 0% validator and the profit (from block production) goes straight to identity account. At the same time users' funds are 100% safe and not affected by the issue in case.

Anyway i have finally got some time and the sign is now gone.
